name: MattFrantz
favicon: null
layout_spectrum: 0.7824070972856134
typography_spectrum: 0.32364873914048076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: Matt Frantz
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.19474436435848475
purpose:
  - name: shares
    item: null
    url: null
